/*
 * File: ZLC_headfile.h
 * ZLC Electronic Design Competition Group（ZLC电赛小组）
 * Zhijian Li,Haoran Chen,Tianyu Zhou
 * Shandong University    2024-10-7
 * Open Source address: https://github.com/ZhijianLi2003/ZLC_MSPM0_Peripheral_Library
 * MSPM0G3507 LaunchPad expansion board:http://oshwhub.com/hurricanchen/zlc_-dian-sai-mspm0g3507-launchpad-kuo-zhan-ban
 */

//C language Official I/O headfile
#include <stdio.h>

//Clock configuration headfile
#include "board.h"

//The configuration headfile generated by the TI system configuration tool
#include "ti_msp_dl_config.h"

//IMU660RA driver headfile(from the merchant)
#include "zf_device_imu660ra.h"

//ZLC_lib
#include "ZLC_poseCalculate.h"
#include "ZLC_Encoder.h"
#include "ZLC_Servo.h"
#include "ZLC_PID.h"
#include "ZLC_Motor.h"
#include "ZLC_GPIO_Peripheral.h"
#include "ZLC_Navigation.h"
#include "ZLC_Key.h"